#!/bin/bash
BRANCH=$1
CMD=$2
echo "============================================================="
echo " [$0]"
echo " - [${BRANCH}] ブランチへの [${CMD}]."
echo "============================================================="

# 保護対象のブランチでない場合、このgit操作を許可(exit 0)
[[ "${BRANCH}" != "master" \
&& "${BRANCH}" != "develop" \
&& "${BRANCH}" != "dotfiles" \
]] && exit 0

echo; echo "> 保護対象のブランチ [${BRANCH}] が指定されています。"

# 単に待たせるだけでも効果あるかもしれない。
# # ttyを取得できない場合、中止(exit 1)。その後のブランチ名入力が出来ないから。
# exec < /dev/tty || (echo "tty取得できないgitクライアントです。CUIから操作して下さい。中止します。" && exit 1)
#
# # ブランチ名を入力させる。入力が正しく無い場合は中止(exit 1)
# echo "> 本当に ${CMD} を実行するには '${BRANCH}' と入力して下さい。"; read ANSWER;
# [[ "${ANSWER}" != "${BRANCH}" ]] && echo "一致しません。中止します。" && exit 1

# 30秒待たせる。その間、CTRL+Cで処理中止できる。
echo; T=30; while [[ $T -gt 0 ]]; do echo "[${CMD}] は $T 秒後に実行します。止めるにはCTRL+Cして下さい。"; sleep 1; T=$(($T - 1)); done

# このgit操作を許可(exit 0)
echo; exit 0

