#!/usr/bin/env bash
get_branch() {
  while read -r _ _ remote_ref _; do
    echo "${remote_ref##refs/heads/}"
  done
}
dir=$(dirname "$0")
branch=$(get_branch)
if ! "$dir"/is_committable_branch "$branch"; then
  exit 1
fi
