#!/usr/bin/env bash
get_branch() {
  while read -r _ _ remote_ref _; do
    echo "${remote_ref##refs/heads/}"
  done
}
echo "---------"
get_branch
echo "---------"
exit 1
dir=$(dirname "$0")
branch=$(get_branch)
if ! "$dir"/may_stop_direct_commit "$branch"; then
  exit 1
fi
