#!/bin/bash

# npxのパスを探す
dir_ar=()
dir_ar+=( ~/.nodenv/shims )
dir_ar+=( /usr/local/bin )
dir_ar+=( ~/.anyenv/envs/nodenv/shims )
dir_ar+=( ~/.asdf/shims )
SECRETLINT=""
for dir in ${dir_ar[@]}; do
  if (type "${dir}/npx" > /dev/null 2>&1); then
    SECRETLINT="${dir}/npx secretlint"
    break
  fi
done

if [[ -z ${SECRETLINT} ]]; then
  IFS=','
  echo "no npx ( ${dir_ar[*]} )."
  exit 1
fi

# NOTE: `sed 's|　|\\　|g'` の目的＝ファイル名に含まれる半角スペースを "\ "に変換する。
FILES=$(git ls-files| sed 's| |\\ |g')
if [ -z "${FILES}" ]; then
  exit 0
fi

echo -e "FILES:"
idx=0; for file in ${FILES}; do echo -n " ${idx}:${file}"; idx=$(expr ${idx} + 1); done
${SECRETLINT} ${FILES}

# npx結果
RET=$?
if [ ${RET} -eq 0 ]; then
  echo -e "\nsecretlint>>> GOOD!👍"
  exit 0
else
  exit 1
fi
