#!/bin/bash

# ----------------
# npxのパスを探す
# ----------------
dir_ar=()
dir_ar+=( ~/.nodenv/shims )
dir_ar+=( /usr/local/bin )
dir_ar+=( ~/.anyenv/envs/nodenv/shims )
dir_ar+=( ~/.asdf/shims )
dir=""
for folder in ${dir_ar[@]}; do
  (type "${folder}/npx" > /dev/null 2>&1) && dir="${folder}" && break
done
[[ -z ${dir} ]] && IFS=',' && echo "no npx was found on any of ( ${dir_ar[*]} )." && exit 1

# ----------------
# npxの実行
# ----------------
# NOTE: `sed 's|　|\\　|g'` の目的＝ファイル名に半角スペースを含む時、エスケープすること。
#FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
FILES=$(git ls-files| sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
echo -e "FILES TO BE CHECKED:"
i=0; for f in ${FILES}; do
  echo -n " ($i)$f"; i=$(expr $i + 1)
done
echo -e "$FILES" | xargs -t ${dir}/npx secretlint

# -------------------
# npxの実行結果の判定
# -------------------
RET=$?
[ $RET -eq 0 ] && echo -e "\nGOOD!👍 secretlint passed successfully." && exit 0

exit 1
