#!/usr/bin/env bash
is_npx_found() {
  if ! type "npx"> /dev/null 2>&1; then
    echo "no npx found."
    exit 1
  fi
}
do_secretlint() {
  if ! git ls-files| sed 's| |\\ |g'| xargs npx secretlint; then
    printf "secretlint NG.\n"
    return 1
  else
    printf "secretlint OK.\n"
    return 0
  fi
}
is_npx_found && do_secretlint
