#!/bin/sh

# brew uninstall tmux neovim direnv rg fzf zsh
brew uninstall tmux neovim direnv rg fzf
rm -rf ~/.pyenv ~/.rbenv ~/.cache/tmux ~/.nvm ~/.cache/zplug
rm -f /usr/local/bin/tmux_battery /usr/local/bin/tmux_wifi

