# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

#[[plugins]]
#repo = 'fishbullet/deoplete-ruby'
#on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

#[[plugins]]
#repo = 'w0rp/ale'
#hook_add = '''
#  let g:ale_fixers = {'ruby': ['rubocop'], }
#  let g:ale_sign_column_always = 1
#
#  let g:ale_lint_on_save = 1
#  let g:ale_lint_on_text_changed = 0
#
#  let g:ale_set_loclist = 0
#  let g:ale_set_quickfix = 1
#  let g:ale_open_list = 1
#  let g:ale_keep_list_window_open = 0
#
#  let g:ale_lint_on_enter = 1
#
#  " vim-airline setting for ale
#  "let g:airline#extensions#ale#enabled = 1
#'''
#on_ft = ['ruby']

