[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = '''
  let g:jedi#auto_initialization    = 0 " Disable the default initialization routine
  let g:jedi#auto_vim_configuration = 0 " Don't change 'completeopt'
  let g:jedi#popup_on_dot           = 0 " Manually press the completion key
  let g:jedi#popup_select_first     = 0 " Don't select first completion entry
  let g:jedi#show_call_signatures   = 0 " Avoid popups bugs
  let g:jedi#goto_command = "<Leader>d"
'''
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'tell-k/vim-autopep8'
hook_add = '''
  let g:autopep8_max_line_length=99
  let g:autopep8_disable_show_diff=1
  autocmd FileType python map <buffer> <F8> :call Autopep8()<CR>
'''
on_ft = ['python']

# Ctags generator for vim
[[plugins]]
repo = 'szw/vim-tags'
hook_add = '''
  let g:vim_tags_project_tags_command = "ctags --langmap=Python:.py --exclude=*.js --exclude=.git* -R . 2>/dev/null"
  set tags+=tags;~/

  " tagsジャンプ時に複数候補ある場合、一覧表示
  nnoremap <C-]> g<C-]>
'''
on_ft = ['python']

