[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rbenv'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rbenv'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

# rsense
[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'
on_ft = ['ruby']
hook_add = '''
  if !exists('g:neocomplcache_omni_patterns')
    let g:neocomplcache_omni_patterns = {}
  endif
  let g:neocomplcache_omni_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'
  autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete

  "rsenseのインストールフォルダがデフォルトと異なるので設定
  let g:rsenseHome = expand("/usr/local/bin/rsense")
  let g:rsenseUseOmniFunc = 1
'''

# Ctags generator for vim
[[plugins]]
repo = 'szw/vim-tags'
hook_add = '''
  let g:vim_tags_project_tags_command = "ctags --langmap=RUBY:.rb --exclude=*.js --exclude=.git* -f ~/.tags -R . 2>/dev/null"
  let g:vim_tags_gems_tags_command =    "ctags --langmap=RUBY:.rb --exclude=*.js --exclude=.git* -R -f ~/.Gemfile.lock.tags `bundle show --paths` 2>/dev/null"
  set tags+=.tags;~/
  set tags+=.Gemfile.lock.tags;~/

  " tagsジャンプ時に複数候補ある場合、一覧表示
  nnoremap <C-]> g<C-]>
'''
on_ft = ['ruby']

# Ruby Completion for deoplete using rcodetools
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Deoplete-Ruby Completion
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

