#!/usr/bin/env bash
if [[ $1 =~ [0-9]+,[0-9]+ ]]; then
  lookup_start=$(echo "$1"| awk -F ',' '{ print $1 }')
  lookup_end=$(echo "$1"| awk -F ',' '{ print $2 }')
else
  lookup_start=$(echo "$1"| awk -F ',' '{ print $1 }')
  lookup_end="$lookup_start"
fi
readonly L=/tmp/a.txt
readonly R=/tmp/b.txt

get_seq_of_diff_hunk() { seq 1 "$(diff "$1" "$2"| grep -Evc "^(<|\-\-\-|>)")"; return 0; }
get_summaries() { diff "$1" "$2"| grep -Ev "^(<|\-\-\-|>)"; return 0; }
get_nth_sum() { get_summaries "$1" "$2"| awk -v n="$3" '{ if (NR==n) { print $0 }}'; return 0; }
get_sumL() { echo "$1"| awk -F '[acd]' '{ print $1 }'; return 0; }
get_sumR() { echo "$1"| awk -F '[acd]' '{ print $2 }'; return 0; }
get_sumstart() { echo "$1"| awk -F ',' '{ print $1 }'; return 0; }
get_sumend() { echo "$1"| awk -F ',' '{ print $2 }'; return 0; }
get_line_of_lineno() { echo "$1"| awk -v lineno_start="$2" -v lineno_end="${3:-$2}" '{ if (lineno_start <= NR && NR <= lineno_end) { print $0 }}'; return 0; }
is_line_no_between() {
  l_lookup_start="$1"
  l_lookup_end="$2"
  start="$3"
  end="$4"
  [[ "$start" -le "$l_lookup_start" && "$l_lookup_end" -le "$end" ]] && return 0 || return 1;
}
numcat() { cat "$1"| awk '{ printf "%2d %s\n", NR, $0 }'; return 0; }

seq_no_lookup_beaten=0
dig() {
  for seq_no in $(get_seq_of_diff_hunk "$L" "$R"); do
    sum=$(get_nth_sum "$L" "$R" "$seq_no")
    sumR=$(get_sumR "$sum")
    sumR_start=$(get_sumstart "$sumR")
    sumR_end=$(get_sumend "$sumR")
    sumR_end=${sumR_end:-$sumR_start}

    if is_line_no_between "$lookup_start" "$lookup_end" "$sumR_start" "$sumR_end"; then
      sumL=$(get_sumL "$sum")
      sumL_start=$(get_sumstart "$sumL")
      if [[ $sum =~ [0-9]+[ad][0-9]+ ]]; then
        sumL_start=$(( sumL_start - 1 ))
      fi

      sumL_end=$(get_sumend "$sumL")
      sumL_end=${sumL_end:-$sumL_start}
      l_results=$(get_line_of_lineno "$(numcat $L)" "$sumL_start" "$sumL_end")
      echo "$l_results"| sed 's/^/[OLDER] /'
      echo "----"
      r_results=$(get_line_of_lineno "$(numcat $R)" "$lookup_start" "$lookup_end")
      echo "$r_results"| sed 's/^/[NEWER] /'
      if [[ $sum =~ [0-9]+[ad][0-9]+ ]]; then
        echo "$l_results"| head -1| awk '{ printf "#%d", $1 }'
      else
        echo "$l_results"| tail -n 1| awk '{ printf "#%d", $1 }'
      fi

      exit 0
    elif [[ "$seq_no_lookup_beaten" -eq 0 && "$lookup_start" -lt "$sumR_start" ]]; then
      seq_no_lookup_beaten="${seq_no}"
    fi
  done

  if [[ "$seq_no_lookup_beaten" -eq 0 ]]; then
    seq_no_lookup_beaten=$(get_seq_of_diff_hunk "$L" "$R"| tail -n 1)
    sum=$(get_nth_sum "$L" "$R" "$((seq_no_lookup_beaten))")
  else
    sum=$(get_nth_sum "$L" "$R" "$((seq_no_lookup_beaten - 1))")
  fi
  echo "sum=$sum"
  sumR=$(get_sumR "$sum")
  sumR_start=$(get_sumstart "$sumR")
  sumR_end=$(get_sumend "$sumR")
  sumR_end=${sumR_end:-$sumR_start}

  sumL=$(get_sumL "$sum")
  sumL_start=$(get_sumstart "$sumL")
  sumL_end=$(get_sumend "$sumL")
  sumL_end=${sumL_end:-$sumL_start}

  left_lineno=$((lookup_start + sumL_end - sumR_end))
  l_results=$(get_line_of_lineno "$(numcat $L)" "$left_lineno" "$((left_lineno + lookup_end - lookup_start))")
  echo "$l_results"| sed 's/^/[OLDER] /'
  echo "----"
  r_results=$(get_line_of_lineno "$(numcat $R)" "$lookup_start" "$lookup_end")
  echo "$r_results"| sed 's/^/[NEWER] /'
  echo "$l_results"| head -1| awk '{ printf "%s", $1 }'

  return 0
}

dig
