#!/usr/bin/env bash
get_content_of() {
  local l_file="$1"
  local l_commit="$2"
  git -c core.quotepath=false -c log.showSignature=false cat-file --filters "${l_commit}:${l_file}"
}

get_commits() {
  local l_file="$1"
  git log --date=iso --pretty="%H" -- "${l_file}"
  return 0
}

get_prev_commit() {
  local l_file="$1"
  local l_commit="$2"
  git log -1 --date=iso --pretty="%H" "${l_commit}^" -- "${l_file}"
}

file=aaa.txt
for new_commit in $(get_commits "${file}"); do
  old_commit=$(get_prev_commit "${file}" "${new_commit}")
  if [[ -n "${old_commit}" ]]; then
    old_content=$(get_content_of "${file}" "${old_commit}")
    git log -1 --date=iso --pretty="OLD %H %ad %s" "${old_commit}" -- "${file}"
  else
    old_content=""
  fi
  new_content=$(get_content_of "${file}" "${new_commit}")
  git log -1 --date=iso --pretty="NEW %H %ad %s" "${new_commit}" -- "${file}"
  diff <(printf "%s" "${old_content}") <(printf "%s" "${new_content}")
  read
done

