#!/bin/bash
readonly EXPECTED=".githooks"

set -x
# ----------------------------
# git hookが動作するための準備
# ----------------------------
# .git/config の core.hooksPath が期待する値でなければ、期待する値を設定する。
core_hookspath="$(git config --local --get core.hooksPath)"
if [[ "${core_hookspath}" != "${EXPECTED}" ]]; then
  git_root="$(git rev-parse --show-superproject-working-tree --show-toplevel 2>&1| head -1)"
  cp "${git_root}/.git/config" "${git_root}/.git/config_bk$(date +'%Y%m%d_%H%M%S')"
  git config --local core.hooksPath "${EXPECTED}"
fi

# -------------------------------
# secretlintが動作するための準備
# -------------------------------
yarn install --save-dev
