[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rbenv'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rbenv'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

# rsense
[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'
on_ft = ['ruby']
hook_add = '''
  if !exists('g:neocomplcache_omni_patterns')
    let g:neocomplcache_omni_patterns = {}
  endif
  let g:neocomplcache_omni_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'
  autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete

  "rsenseのインストールフォルダがデフォルトと異なるので設定
  let g:rsenseHome = expand("/usr/local/bin/rsense")
  let g:rsenseUseOmniFunc = 1
'''

# Ruby Completion for deoplete using rcodetools
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Deoplete-Ruby Completion
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

