[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = '''
  let g:jedi#auto_initialization    = 0 " Disable the default initialization routine
  let g:jedi#auto_vim_configuration = 0 " Don't change 'completeopt'
  let g:jedi#popup_on_dot           = 0 " Manually press the completion key
  let g:jedi#popup_select_first     = 0 " Don't select first completion entry
  let g:jedi#show_call_signatures   = 0 " Avoid popups bugs
'''
#on_ft = ['python']

[[plugins]]
repo = 'tell-k/vim-autopep8'
hook_add = '''
  let g:autopep8_max_line_length=99
  let g:autopep8_disable_show_diff=1
  autocmd FileType python map <buffer> <F8> :call Autopep8()<CR>
'''
#on_ft = ['python']

