
# icon
set -g @cpu_low_icon     "="
set -g @cpu_medium_icon  "="
set -g @cpu_high_icon    "="

# fg_color
set -g @cpu_low_fg_color    ""
set -g @cpu_medium_fg_color ""
set -g @cpu_high_fg_color   ""

# bg_color
set -g @cpu_low_bg_color    ""
set -g @cpu_medium_bg_color ""
set -g @cpu_high_bg_color   ""

# cpu-percentage
set -g @cpu_percentage_format "%2.0f%%" # printf format to use to display percentage
