# [ステータスバー(左側)]
set -g status-left-length  80
set -g  status-left '#{?client_prefix,#[reverse],}'
set -ga status-left 'SES[#S/#(~/dotfiles/bin/tmux/tmux_sessions_count)]'
set -ga status-left '|'
set -ga status-left '#{?client_prefix,#[reverse],}'
set -ga status-left ' '
set -ga status-left '#(~/dotfiles/bin/tmux/tmux_current_datetime)'
set -ga status-left  '|'
set -ga status-left ' '
set -ga status-left 'BAT'
set -ga status-left '#(~/dotfiles/bin/tmux/tmux_battery)'
set -ga status-left '#{?client_prefix,#[reverse],}'
set -ga status-left '|'
set -ga status-left ' '
set -ga status-left "#[reverse]#{simple_git_status}#[default] "
