# [プラグイン]
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'tmux-plugins/tmux-copycat'
# set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-urlview'
# set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'schasse/tmux-jump'

# --------
set -g @jump-key 'e'
set -g @jump-keys-position 'left'
# --------

set -g @urlview-key 'u'

# tmux-yank
set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default
#set -g @yank_action 'copy-pipe-and-cancel' # or 'copy-pipe-and-cancel' for the default

# [tmux-cpu]
# cpu-low
set -g @cpu_low_icon     "="
set -g @cpu_medium_icon  "="
set -g @cpu_high_icon    "="

set -g @cpu_low_fg_color    ""
set -g @cpu_medium_fg_color ""
set -g @cpu_high_fg_color   ""

set -g @cpu_low_bg_color    ""
set -g @cpu_medium_bg_color ""
set -g @cpu_high_bg_color   ""

# cpu-percentage
set -g @cpu_percentage_format "%2.0f%%" # printf format to use to display percentage
