# ステータスバー(右側)
set -g status-right-length 200
set -g  status-right '#{?pane_mode,  [#{pane_mode}]  ,}'
set -ga status-right '#{?client_prefix,#[reverse],}'
set -ga status-right ' '
set -ga status-right 'CPU'

set -g @cpu_low_icon    ":"
set -g @cpu_medium_icon ":"
set -g @cpu_high_icon   ":"
set -ga status-right '#{cpu_icon}'
set -ga status-right '#{cpu_percentage}'
set -ga status-right '#{?client_prefix,#[reverse],}'
set -ga status-right ','
set -ga status-right '#(~/dotfiles/bin/tmux/tmux_memory)'
set -ga status-right '#{?client_prefix,#[reverse],}'
set -ga status-right ','
set -ga status-right 'SSD:'
set -ga status-right '#(~/dotfiles/bin/tmux/tmux_df_avail)'
set -ga status-right '#{?client_prefix,#[reverse],}'
set -ga status-right ' '

