set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'kristijanhusak/tmux-simple-git-status'

source-file ~/dotfiles/.config/tmux/tmux-plugin-cpu.conf
source-file ~/dotfiles/.config/tmux/tmux-plugin-urlview.conf
source-file ~/dotfiles/.config/tmux/tmux-plugin-jump.conf
