# ペイン
set -g pane-border-style         'bg=colour238'
set -g pane-active-border-style  'bg=colour238'
set -g  pane-border-lines simple
set -g  pane-border-status top

set -g  pane-border-format '#[fg=colour187]'
set -ga pane-border-format 'PANE[#I-#P#{?window_zoomed_flag,#[bg=colour88]:zoomed#[default],}] # #{pane_current_command} '
set -ga pane-border-format '#[default]'
