# [ステータスバー(ウインドウ。これはstatus-leftの右隣)]
setw -g  window-status-format '#{?client_prefix,#[reverse],}'
setw -ga window-status-format '#I#W'
setw -ga window-status-format '#{?window_zoomed_flag,#[bg=colour88]:zoomed#[default],}'
setw -ga window-status-format '|'
setw -g  window-status-current-format '#{?client_prefix,#[reverse ],}'
setw -ga window-status-current-format '#[curly-underscore]'
setw -ga window-status-current-format '#I,#W'
setw -ga window-status-current-format '#[default]'
setw -ga window-status-current-format '#{?window_zoomed_flag,#[bg=colour88]#[curly-underscore]:zoomed#[default],}'
setw -ga window-status-current-format '#[default]'
setw -ga window-status-current-format '|'

