# [ステータスバー(ウインドウ。これはstatus-leftの右隣)]

# 非アクティブウインドウ
setw -g  window-status-format ''
setw -ga window-status-format '(#{?window_zoomed_flag,*, }'
setw -ga window-status-format '#{P:#{pane_current_command} }'
setw -ga window-status-format ')'

# アクティブウインドウ
setw -g  window-status-current-format ''
setw -ga window-status-current-format '(#{?window_zoomed_flag,*, }'
setw -ga window-status-current-format '#{P:#{?pane_active,#[reverse],}#{pane_current_command}#[default] }'
setw -ga window-status-current-format ')'
