set -g @plugin 'tmux-plugins/tpm'

source-file ~/dotfiles/.config/tmux/tmux-plugin-cpu.conf
source-file ~/dotfiles/.config/tmux/tmux-plugin-urlview.conf
source-file ~/dotfiles/.config/tmux/tmux-plugin-jump.conf
