call pum#set_option('border', 'single')
call pum#set_option('highlight_columns', #{ })
call pum#set_option('auto_select', v:true)
call pum#set_option('max_width', 0)
call pum#set_option('max_height', 15)
call pum#set_option('auto_confirm_time', 0)
call pum#set_option('scrollbar_char', ' ')
call pum#set_option('preview', v:true)
call pum#set_option('preview_border', 'single')
call pum#set_option('preview_width', 100)
call pum#set_option('preview_delay', 0)
