[[plugins]]
repo='tyru/open-browser.vim'
hook_add='''
nmap @ <Nop>
nmap @g <Plug>(openbrowser-search)
nmap <C-@> <Plug>(openbrowser-smart-search)
nnoremap @a :<C-u>execute 'OpenBrowserSearch -alc' expand('<cWORD>')<CR>
nnoremap @d :<C-u>execute 'OpenBrowserSearch -dev' expand('<cWORD>')<CR>
let g:openbrowser_search_engines = {
    \ 'alc': 'http://eow.alc.co.jp/{query}/UTF-8/',
    \ 'dev': 'https://dev.classmethod.jp/?s={query}',
    \ }

'''
