[[plugins]]
repo = 'fholgado/minibufexpl.vim'
hook_add = '''
  let g:miniBufExplorerAutoStart = 1
  let g:miniBufExplMapWindowNavVim = 1
  let g:miniBufExplMapWindowNavArrows = 1
  "let g:miniBufExplMapCTabSwitchBufs = 1
  "let g:miniBufExplModSelTarget = 1
  "let g:miniBufExplSplitToEdge = 1

  " g:miniBufExplVSplitに1以上の数値を設定すると、配置が垂直方向になる。0を設定すると配置が水平方向になる。

  "" " 左配置
  "" let g:miniBufExplVSplit = 20
  "" let g:miniBufExplSplitBelow = 0

  "" " 右配置
  "" let g:miniBufExplVSplit = 20
  "" let g:miniBufExplSplitBelow = 1

  "" " 上配置
  "" let g:miniBufExplVSplit = 0
  "" let g:miniBufExplSplitBelow = 0

  " 下配置
  let g:miniBufExplVSplit = 0
  let g:miniBufExplSplitBelow = 1
'''

