# vim の素のfの方が使いやすい気がしたのでコメントアウト
# 
# # ノーマルモードでf押下でプラグイン起動
# # ジャンプしたい先の文字を2文字入力でジャンプ候補表示
# # 説明が難しいが、試せばわかる。
# [[plugins]]
# repo = 'easymotion/vim-easymotion'
# hook_add = '''
# let g:EasyMotion_do_mapping = 1
# let g:EasyMotion_keys = ';HKLYUIOPNM,QWERTASDGZXCVBJF'
# let g:EasyMotion_keys = ';HKLYUIOPNM,QWERTASDGZXCVBJF'
# " Show target key with upper case to improve readability
# let g:EasyMotion_use_upper = 1
# " Jump to first match with enter & space
# "let g:EasyMotion_enter_jump_first = 1
# "let g:EasyMotion_space_jump_first = 1
# nmap f <Plug>(easymotion-s)
# '''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add='''
  let g:clever_f_mark_direct = 1
'''


[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  let g:accelerated_jk_acceleration_table = [7,12,17,21,24,26,28,30]
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

