[[plugins]]
repo = 'ippsio/clip_diff.vim'
hook_add = '''
  vmap ,d :call ClipDiff()<CR>
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  " let g:accelerated_jk_enable_deceleration = get(g:, 'accelerated_jk_enable_deceleration', 0)
  " let g:accelerated_jk_acceleration_limit = get(g:, 'accelerated_jk_acceleration_limit', 150)
  " let g:accelerated_jk_acceleration_table = [7,12,17,21,24,26,28,30]
  "let g:accelerated_jk_acceleration_table = [4,6,8,11,12,13,14,15]
  "let g:accelerated_jk_acceleration_table = [14,24,34,42,48,52,56,60]
  "let g:accelerated_jk_acceleration_table = [15,100,150]
  let g:accelerated_jk_acceleration_table = [10,20,150]
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''
