# 終了タグ等の自動補完
[[plugins]]
repo = 'tpope/vim-endwise'

# 文字をシングルクォートとか（）で囲む
[[plugins]]
repo = 'tpope/vim-surround'

# インサートモードで行番号をハイライトONし、状態をわかりやすくする
[[plugins]]
repo = 'cohama/vim-insert-linenr'

[[plugins]]
repo = 'rhysd/accelerated-jk'
