#[[plugins]]
#repo = 'vim-scripts/SQLUtilities'
#[[plugins]]
#repo= 'vim-scripts/Align'
[[plugins]]
repo = 'b4b4r07/vim-sqlfmt'
[[plugins]]
repo = 'jackc/sqlfmt'
[[plugins]]
repo = 'andialbrecht/sqlparse'
