###fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all --no-bash --no-fish --no-zsh'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.9 } }

  " バッファ一覧をfzfで絞り込む
  nnoremap ; :Buffers<CR>


  " 現在開いてるファイルがgit管理下ならそのディレクトリを、そうでなければ現在のパスを返す。
  function! s:GetDir(args0)
    if a:args0 != ''
      if isdirectory(a:args0)
        return a:args0
      else
        throw 'ディレクトリ ['.a:args0.'] っつうのが見つからない。'
      endif
    else
      let s:git_root = system('cd ' . expand('%:p:h') . '; git rev-parse --show-toplevel 2> /dev/null')[:-2]
      return s:git_root != '' ? s:git_root : expand('%:p:h')
    endif
  endfunction

  nnoremap <silent> // :BLinesWithPreview<CR>
  "nnoremap <space>m :BLines module\ \\|class\ \\|\ def\ \\|before_action\ \\|protect_from_forgery\ \\|helper_method\ <CR>
  "nnoremap <space>m :<C-u>:BLinesWithPreview module \| class \| def \| before_action \| protect_from_forgery \| helper_method <CR>
  command! -bang -nargs=* BLinesWithPreview
    \ call fzf#vim#grep(
    \   'rg --with-filename --line-number --no-heading --smart-case . '.fnameescape(expand('%:p')), 1,
    \   fzf#vim#with_preview({'options': '--layout reverse --query '.shellescape(<q-args>).' --with-nth=2.. --nth=2.. --delimiter=":"'}, 'down:50%'))

  " ファイル名の一覧をfzfで絞り込む
  nnoremap <C-p> :FzfFiles<CR>
  command! -bang -nargs=? -complete=dir FzfFiles
        \ call fzf#run(fzf#vim#with_preview(fzf#wrap({
        \   'source': 'find -s -E . -not -regex ".*(\.DS_Store|/*.git/).*" -and -type f',
        \   'dir': s:GetDir(<q-args>),
        \ })))

  " ファイルの内容をripgrepで検索して、さらにfzfで絞り込む
  command! -bang -nargs=* Grep
        \ call fzf#vim#grep(
        \   'rg --hidden --sortr path --column --ignore=.git ' . shellescape(<q-args>),
        \   1,
        \   <bang>0
        \     ? fzf#vim#with_preview({'window:enew'})
        \     : fzf#vim#with_preview({'window':'enew' ,'dir': s:GetDir('')}),
        \   <bang>0
        \ )
'''
