###fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all --no-bash --no-fish --no-zsh'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  let g:fzf_layout = {'window': { 'width': 0.95, 'height': 0.95 } }
  " " Default fzf layout
  " " - Popup window (center of the screen)
  " let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
  " " - Popup window (center of the current window)
  " let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'relative': v:true } }
  " " - Popup window (anchored to the bottom of the current window)
  " let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'relative': v:true, 'yoffset': 1.0 } }
  " " - down / up / left / right
  " let g:fzf_layout = { 'down': '40%' }
  " " - Window using a Vim command
  " let g:fzf_layout = { 'window': 'enew' }
  " let g:fzf_layout = { 'window': '-tabnew' }
  " let g:fzf_layout = { 'window': '10new' }

  " バッファ一覧をfzfで絞り込む
  nnoremap ; :Buffers<CR>

  " 現在開いてるファイルがgit管理下ならそのディレクトリを、そうでなければ現在のパスを返す。
  function! s:GetDir(args0)
    if a:args0 != ''
      if isdirectory(a:args0)
        return a:args0
      else
        throw 'ディレクトリ ['.a:args0.'] っつうのが見つからない。'
      endif
    else
      let s:git_root = system('cd ' . expand('%:p:h') . '; git rev-parse --show-toplevel 2> /dev/null')[:-2]
      return s:git_root != '' ? s:git_root : expand('%:p:h')
    endif
  endfunction

  "nnoremap <silent> ' :<C-u>:BLinesWithPreview  def <CR>
  "nnoremap <silent> ? :<C-u>:BLinesWithPreview<CR>
  " NOTE: ここでのシングルクォートによるremapは、
  " ハイライト一覧の閲覧「:so $VIMRUNTIME/syntax/hitest.vim」実行時にバッティングします。
  " ハイライト一覧を見たい場合、このnnoremap は一旦コメントアウトしましょう...。
  nnoremap <silent> ' :<C-u>:BLinesWithPreview<CR>
  command! -bang -nargs=* BLinesWithPreview
        \ call fzf#vim#grep(
        \   'rg --with-filename --line-number --no-heading --smart-case . '.fnameescape(expand('%:p')),
        \   1,
        \   fzf#vim#with_preview(
        \     {'options': '--prompt="' . expand('%:p:h') . ' > " --info=inline --layout reverse --query '.shellescape(<q-args>).' --with-nth=2.. --nth=2.. --delimiter=":"'},
        \     'down:50%'
        \   )
        \ )

  " ファイル名の一覧をfzfで絞り込む
  nnoremap <C-p> :FzfFiles<CR>
  command! -bang -nargs=? -complete=dir FzfFiles
        \ call fzf#run(
        \   fzf#vim#with_preview(
        \     fzf#wrap(
        \       {
        \         'dir': s:GetDir(<q-args>),
        \         'source': 'find -s -E . -not -regex ".*(\.DS_Store|/*.git/).*" -and -type f'
        \       }
        \     )
        \   )
        \ )

  " ファイルの内容をripgrepで検索して、さらにfzfで絞り込む
  command! -bang -nargs=* Grep
        \ call fzf#vim#grep(
        \   'rg --color=always --with-filename --line-number --no-heading --hidden --sortr path --ignore=.git ' . shellescape(<q-args>),
        \   1,
        \   fzf#vim#with_preview(
        \     {'options': '--prompt="filter > " --info=inline --layout reverse --with-nth=1.. --nth=1.. --delimiter=":"'}
        \   )
        \ )
'''

# \     ? fzf#vim#with_preview({'window:enew'})
# \     : fzf#vim#with_preview({'window':'enew' ,'dir': s:GetDir('')}),
