[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <space>a :Git blame<CR>
  command! -nargs=0 GD call s:GitDiff()
  function! s:GitDiff()
    if $GIT_MERGE_BASE != ""
      echo 'Gvdiffsplit ' . $GIT_MERGE_BASH
      Gvdiffsplit $GIT_MERGE_BASH
    else
      echo 'Gvdiffsplit HEAD^'
      Gvdiffsplit HEAD^
    endif
  endfunction
  augroup FugitiveAutocmd
    autocmd!
    " fugitive の blame だけになった時、quitする。
    autocmd WinEnter * if winnr('$') == 1 && expand('%p') =~ '.fugitiveblame' | quit | endif
  augroup END
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  " 変更マーク
  let g:gitgutter_sign_added              = '+'
  let g:gitgutter_sign_modified           = '~'
  let g:gitgutter_sign_removed            = 'X'
  let g:gitgutter_sign_removed_first_line = '_^'
  let g:gitgutter_sign_modified_removed   = '~R'

  " 変更マークのハイライト
  hi SignColumn             ctermbg=none
  hi GitGutterAdd           ctermfg=118 ctermbg=23  "cterm=bold " an added line
  hi GitGutterChange        ctermfg=11  ctermbg=59 "cterm=bold " a changed line
  hi GitGutterDelete        ctermfg=8   ctermbg=232 "cterm=bold " at least one removed line
  hi GitGutterChangeDelete  ctermfg=8   ctermbg=232 "cterm=bold " a changed line followed by at least one removed line

  " 行ハイライトは結構見にくいと感じたので、コメントアウト
  "" 起動時に差分行の行ハイライトを自動的に有効にする
  "" let g:gitgutter_highlight_lines = 1

  " 行番号のハイライト
  "let g:gitgutter_highlight_linenrs = 1

  augroup GitGutter
    autocmd!
    " 何かバッファを開いたら、gitgutterのサイン表示に利用するgitの比較元ハッシュを更新する
    autocmd BufEnter * call s:UpdateMergeBase()
    function! s:UpdateMergeBase()
      if $GIT_MERGE_BASE != ""
        let g:gitgutter_diff_base = $GIT_MERGE_BASE
      endif
      GitGutter
    endfunction
  augroup END

  " 比較対象(diff_base)を変更するコマンド
  " 使い方:
  "   :GGCB develop[enter] など
  command! -nargs=1 GGCB call s:change_base(<f-args>)
  function! s:change_base(diff_base)
    let g:gitgutter_diff_base = a:diff_base
    GitGutter
  endfunction
'''

[[plugins]]
repo = 'rhysd/conflict-marker.vim'
hook_add='''
" disable the default highlight group
let g:conflict_marker_highlight_group = ''

" Include text after begin and end markers
let g:conflict_marker_begin = '^<<<<<<< .*$'
let g:conflict_marker_end   = '^>>>>>>> .*$'

highlight ConflictMarkerBegin cterm=bold ctermfg=5 ctermbg=53
highlight ConflictMarkerOurs ctermbg=53
highlight ConflictMarkerTheirs ctermbg=4
highlight ConflictMarkerEnd cterm=bold ctermfg=18 ctermbg=4
highlight ConflictMarkerCommonAncestorsHunk ctermbg=166
'''

