# 他のキーバインドとしばしば競合する？
# # 文字をシングルクォートとか（）で囲む
# [[plugins]]
# repo = 'tpope/vim-surround'
# hook_add='''
#   xmap " S"
#   xmap ' S'
#   xmap ) S)
#   xmap } S}
#   xmap ] S]
#   xmap > S>
# '''

[[plugins]]
repo = 'tpope/vim-repeat'
on_idle = 1

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
map _ <Plug>(operator-replace)
'''


