[[plugins]]
repo = 't9md/vim-choosewin'
hook_add = '''
  " どちらのキーバインドが使いやすいか、検討中
  nmap <silent> -        <Plug>(choosewin)
  nmap <silent> <space>c <Plug>(choosewin)

  " オーバーレイ機能を有効にしたい場合
  let g:choosewin_overlay_enable = 1

  " オーバーレイ・フォントをマルチバイト文字を含むバッファでも綺麗に表示する。
  let g:choosewin_overlay_clear_multibyte = 1
'''
