###fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all --no-bash --no-fish --no-zsh'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap [fzf] <Nop>
  nmap ; [fzf]

  " バッファ一覧をfzfで絞り込む
  nnoremap [fzf]; :Buffers<CR>

  " 現在のファイル内の文字を探す
  nnoremap [fzf]l :Lines<CR>

  " 現在開いてるファイルがgit管理下ならそのディレクトリを、そうでなければ現在のパスを返す。
  function! s:GetDir(args0)
    if a:args0 != ''
      if isdirectory(a:args0)
        return a:args0
      else
        throw 'ディレクトリ ['.a:args0.'] っつうのが見つからない。'
      endif
    else
      let s:git_root = system('cd ' . expand('%:p:h') . '; git rev-parse --show-toplevel 2> /dev/null')[:-2]
      return s:git_root != '' ? s:git_root : expand('%:p:h')
    endif
  endfunction

  " ファイル名の一覧をfzfで絞り込む
  nnoremap <C-p> :FzfFiles<CR>
  nnoremap [fzf]f :FzfFiles
  command! -bang -nargs=? -complete=dir FzfFiles
        \ call fzf#run(fzf#vim#with_preview(fzf#wrap({
        \   'source': 'find -s -E . -not -regex ".*(\.DS_Store|/*.git/).*" -and -type f',
        \   'dir': s:GetDir(<q-args>),
        \   'window': 'enew'
        \ })))

  " ファイルの内容をripgrepで検索して、さらにfzfで絞り込む
  nnoremap <C-h> :FzfGrep
  nnoremap [fzf]g :FzfGrep<CR>
  command! -bang -nargs=* FzfGrep
        \ call fzf#vim#grep(
        \   'rg --hidden --sortr path --column --ignore=.git ' . shellescape(<q-args>),
        \   1,
        \   <bang>0
        \     ? fzf#vim#with_preview({'window:enew'})
        \     : fzf#vim#with_preview({'window':'enew' ,'dir': s:GetDir('')}),
        \   <bang>0
        \ )
'''
