[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = '''
  " ビジュアルモードの選択中に#で選択中の文字列をハイライトしつつ置換モード(:%s/xxx/xxx/)に入る
  xnoremap # mz:call <SID>set_Vsearch()<CR>`z:OverCommandLine<CR>%s/<C-r>///g<Left><Left>
  function! s:set_Vsearch()
    normal gv"zy
    let @/ = '\V' . substitute(escape(@z, '/\'), '\n', '\\n', 'g')
  endfunction
'''
