# /検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  " let g:anzu_status_format = "%p(%i/%l)"
  let g:anzu_status_format = "%i/%l"

  " nmap n nzz<Plug>(anzu-mode-n)
  " nmap N Nzz<Plug>(anzu-mode-N)
  nmap n nzz<Plug>(anzu-update-search-status)
  nmap N Nzz<Plug>(anzu-update-search-status)
  xmap n <Esc>ngN
  xmap N <Esc>NgN
  nmap * <Plug>(anzu-star)
  "nmap # <Plug>(anzu-sharp)
  nmap <silent> <ESC> :<C-u>nohlsearch<CR><Plug>(anzu-clear-search-status)
'''
