# /検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n nzz<Plug>(anzu-update-search-status)
  nmap N Nzz<Plug>(anzu-update-search-status)
  xmap n <Esc>ngN
  xmap N <Esc>NgN
  nmap * <Plug>(anzu-star)
  "nmap # <Plug>(anzu-sharp)
  nmap <silent> <ESC> :<C-u>nohlsearch<CR><Plug>(anzu-clear-search-status)
'''
