###fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all --no-bash --no-fish --no-zsh'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  " バッファ一覧から
  nnoremap fb :Buffers<CR>

  " 現在のファイル内の文字を探す
  nnoremap fl :Lines<CR>

  " ファイル名で探す
  nnoremap ff :Files<CR>
  nnoremap <C-p> :Files<CR>
  command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)

  " ファイルの内容をripgrepで検索して、さらにfzfで絞り込む
  nnoremap fg :Grep<CR>
  command! -bang -nargs=* Grep call fzf#vim#grep('rg --sortr path --column --ignore=.git '.shellescape(<q-args>), 1, <bang>0 ? fzf#vim#with_preview('down:80%') : fzf#vim#with_preview({ 'dir': system('git rev-parse --show-toplevel 2> /dev/null')[:-2] }), <bang>0)
'''
