[[plugins]]
repo = 'pechorin/any-jump.vim'
hook_add = '''
  nnoremap <silent> <F3> :AnyJump<CR>
  vnoremap <silent> <F3> :AnyJumpVisual<CR>

  " Show line numbers in search rusults
  let g:any_jump_list_numbers = 0

  " Auto search references
  let g:any_jump_references_enabled = 1

  " Auto group results by filename
  let g:any_jump_grouping_enabled = 0

  " Amount of preview lines for each search result
  let g:any_jump_preview_lines_count = 5

  " Max search results, other results can be opened via [a]
  let g:any_jump_max_search_results = 100

  " Prefered search engine: rg or ag
  let g:any_jump_search_prefered_engine = 'rg'

  " Search results list styles:
  " - 'filename_first'
  " - 'filename_last'
  let g:any_jump_results_ui_style = 'filename_first'

  " Any-jump window size & position options
  let g:any_jump_window_width_ratio  = 0.9
  let g:any_jump_window_height_ratio = 0.8
  let g:any_jump_window_top_offset   = 3

  " Customize any-jump colors with extending default color scheme:
  let g:any_jump_colors = { "help": "Comment" }

  " Or override all default colors
  let g:any_jump_colors = {
        \"plain_text":         "Comment",
        \"preview":            "Comment",
        \"preview_keyword":    "Operator",
        \"heading_text":       "rubyMacro",
        \"heading_keyword":    "rubyMacro",
        \"group_text":         "",
        \"group_name":         "",
        \"more_button":        "Operator",
        \"more_explain":       "Comment",
        \"result_line_number": "Statement",
        \"result_text":        "Statement",
        \"result_path":        "",
        \"help":               ""
        \}

  " Disable default any-jump keybindings (default: 0)
  " let g:any_jump_disable_default_keybindings = 1

  " Remove comments line from search results (default: 1)
  let g:any_jump_remove_comments_from_results = 1

  " Custom ignore files
  " default is: ['*.tmp', '*.temp']
  let g:any_jump_ignored_files = ['*.tmp', '*.temp']

  " Search references only for current file type
  " (default: false, so will find keyword in all filetypes)
  let g:any_jump_references_only_for_current_filetype = 0

  " Disable search engine ignore vcs untracked files
  " (default: false, search engine will ignore vcs untracked files)
  let g:any_jump_disable_vcs_ignore = 0
'''
