# /検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n nzz<Plug>(anzu-update-search-status)
  nmap N Nzz<Plug>(anzu-update-search-status)
  xmap n <Esc>ngN
  xmap N <Esc>NgN
  nmap * <Plug>(anzu-star)
  "nmap # <Plug>(anzu-sharp)
  nmap <silent> <ESC> :<C-u>nohlsearch<CR><Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = '''
  " over.vimの起動
  nnoremap <silent> <space>over :OverCommandLine<CR>

  " ビジュアルモードの選択中に#で選択中の文字列をハイライトしつつ置換モード(:%s/xxx/xxx/)に入る
  xnoremap # mz:call <SID>set_vsearch()<CR>:set hlsearch<CR>`z:OverCommandLine<CR>:%s/<C-r>///g<Left><Left>
  function! s:set_vsearch()
    silent normal gv"zy
    let @/ = '\V' . substitute(escape(@z, '/\'), '\n', '\\n', 'g')
  endfunction
'''

# ノーマルモードでf押下でプラグイン起動
# ジャンプしたい先の文字を2文字入力でジャンプ候補表示
# 説明が難しいが、試せばわかる。
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_keys = ';HKLYUIOPNM,QWERTASDGZXCVBJF'
  let g:EasyMotion_keys = ';HKLYUIOPNM,QWERTASDGZXCVBJF'
  " Show target key with upper case to improve readability
  let g:EasyMotion_use_upper = 1
  " Jump to first match with enter & space
  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1
  nmap  f <Plug>(easymotion-s2)
'''

###fzf
[[plugins]]
repo = 'junegunn/fzf'
#build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  nnoremap <C-p> :FZFFileList<CR>
  map <silent> <space>e :FZFFileList<CR>

  command! FZFFileList
  \ call fzf#run(fzf#wrap(
  \   {
  \    'source': 'find . -type d -name .git -prune -o ! -name .DS_Store',
  \    'down': '40%'
  \   }
  \ ))

  command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg -g !.git
  \     --column
  \     --line-number
  \     --hidden
  \     --ignore-case
  \     --no-heading
  \     --color=always
  \   '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview(
  \     {
  \       'options': '--exact --reverse'
  \     },
  \     'right:50%:wrap', '?'
  \   )
  \ )
'''


