# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  if !has('gui_running')
    set t_Co=256
  endif

  set laststatus=2
  "let g:lightline_colorscheme = 'Tomorrow_Night_Bright'
  let g:lightline_colorscheme = 'powerline'
  let g:lightline = {
    \  'colorscheme': g:lightline_colorscheme,
    \  'inactive': {
    \    'left': [ ['mode', 'paste'], ['readonly', 'filepath']],
    \    'right': [ [ 'lineinfo' ]]
    \  },
    \  'active': {
    \    'left': [ ['mode', 'paste'], ['readonly', 'filepath']],
    \    'right': [ [ 'lineinfo' ], ['info'] ]
    \  },
    \  'mode_map': {
    \    'n': 'N',
    \    'i': 'I',
    \    'R': 'R',
    \    'v': 'V',
    \    'V': 'V',
    \    "\<C-v>": 'V',
    \    'c': 'C',
    \    's': 'S',
    \    'S': 'S',
    \    "\<C-s>": 'S',
    \    't': 'TERMINAL'
    \  },
    \  'component': { 'lineinfo': '%l/%L(%p%%):%v%<', 'info': '%{%StrGitMergeBase()%}(%{%StrUnderCursor()%} 0x%02B)' . &fileformat . '|' . &fileencoding . '%<'},
    \  'component_function': { 'filepath': 'FileName', 'git': 'StrGitMergeBase'}
    \ }

  function! FileName()
    return substitute(expand("%:p"), $HOME, "~", "g") . ( &modified ? '|+' : '')
  endfunction

  function! StrUnderCursor()
    let l:str = matchstr(getline('.'), '.', col('.')-1)
    " if (l:str == "")
    "   let l:str = "'' "
    " else
    "   let l:str = "'" . l:str . "'"
    " endif
    return l:str
  endfunction

  function! StrGitMergeBase()
    return g:gitgutter_diff_base != "" ? '[' . g:gitgutter_diff_base . ']' : ''
  endfunction
'''

