[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  let g:expand_region_text_objects = {'ie': 0, 'ip': 0, 'iw': 0, 'iB': 1, 'il': 0, 'iW': 0, 'i''': 0, 'ib': 1, 'i]': 1, 'i"': 0}
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
'''
#depends = ['kana/vim-textobj-user', 'kana/vim-textobj-line', 'kana/vim-textobj-entire']

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'kana/vim-textobj-entire'
