# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  if !has('gui_running')
    set t_Co=256
  endif

  set laststatus=2
  let g:lightline_colorscheme = 'PaperColor_dark'
  let g:lightline = {
    \  'colorscheme': g:lightline_colorscheme,
    \  'inactive': {'left': [['mode', 'paste'], ['readonly', 'filepath', 'modified', 'anzu']]},
    \  'active': {
    \    'left': [ ['mode', 'paste'],
    \              ['readonly', 'filepath', 'modified', 'anzu'],
    \              []
    \            ],
    \   'right': [ [ 'lineinfo', 'percent' ],
    \              [ 'diff_base' ],
    \              [ 'fileformat', 'fileencoding', 'filetype']
    \            ]
    \  },
    \  'component_function': {
    \     'anzu': 'anzu#search_status',
    \     'filepath': 'FPath',
    \     'diff_base': 'GitGutterDiffBase'
    \   }
    \ }
  function! FPath()
    return expand("%:s")
  endfunction

  function! GitGutterDiffBase()
    let s:curr_branch = fugitive#statusline()[5:-3]
    echo s:curr_branch
    return "" . g:gitgutter_diff_base . "[BASE]<==[HEAD]" . s:curr_branch
  endfunction
'''

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

