# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add='''
  "" defxを開いた時にハイライトされるのを防ぐ。
  "let g:extra_whitespace_ignored_filetypes = ['defx']
  "autocmd FileType defx match ExtraWhitespace /^^/

  " defxを開いた時にハイライトされるのを防ぐ。
  augroup trailing-whitespace-vs-defx
    autocmd!
    autocmd BufRead,BufEnter,BufWinEnter * if match(["defx"], &ft) >= 0|match ExtraWhitespace /^^/ |endif
  augroup END
'''
