[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#323232 ctermbg=235
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#373739 ctermbg=237
'''

