# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  if !has('gui_running')
    set t_Co=256
  endif

  set laststatus=2
  let g:lightline_colorscheme = 'PaperColor_dark'
  let g:lightline = {
    \ 'colorscheme': g:lightline_colorscheme,
    \ 'inactive': {'left': [['mode', 'paste'], ['readonly', 'filepath', 'modified', 'anzu']]},
    \ 'active': {'left': [['mode', 'paste'], ['readonly', 'filepath', 'modified', 'anzu']]},
    \ 'component_function': {'anzu': 'anzu#search_status', 'filepath': 'FPath'}}

  function! FPath()
    return expand("%:s")
  endfunction
'''

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

