[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=235
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=237
'''

# インサートモードで行番号をハイライトONし、状態をわかりやすくする
#[[plugins]]
#repo = 'cohama/vim-insert-linenr'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add='''
  " hi ExtraWhitespace ctermbg=darkred

  " defxを開いた時にハイライトされるのを防ぐ。
  let g:extra_whitespace_ignored_filetypes = ['defx']
'''

# 対応する括弧をいいかんじにする
[[plugins]]
repo='itchyny/vim-parenmatch'
hook_add='''
let g:loaded_matchparen = 1
let g:parenmatch_highlight = 1

"  if !get(g:, 'parenmatch_highlight', 1) | return | endif
"  highlight ParenMatch term=underline cterm=underline gui=underline
hi ParenMatch term=NONE cterm=NONE gui=NONE
hi ParenMatch ctermbg=57
'''

# カーソル下の単語に下線を引いたり、背景色を変えたりする。
[[plugins]]
repo='itchyny/vim-cursorword'
hook_add='''
"OPTIONS            *cursorword-options*
"
"  g:cursorword        *g:cursorword*
"    Set this variable to 0 to disable this plugin globally.
"
"  b:cursorword        *b:cursorword*
"    If you set this variable to 0, the plugin stops highlighting
"    the word under the cursor in the buffer. This variable has
"    priority over |g:cursorword|.
"
"  g:cursorword_highlight      *g:cursorword_highlight*
"    Set this variable to 0 to disable the default highlighting
"    style. If you set this variable to 0, you need to define your
"    own style for the CursorWord |highlight-groups|.
"
"  g:cursorword_delay      *g:cursorword_delay*
"    The delay duration in milliseconds for setting the word
"    highlight after cursor motions. When the value is set to 0, the
"    plugin highlights the word synchronously, but there is a
"    performance sacrifice. The default value is 50.

let g:cursorword_delay=50
let g:cursorword_highlight=0
hi CursorWord ctermbg=237 cterm=underline
'''

