# [[plugins]]
# repo = 'tpope/vim-markdown'
# on_ft = ['markdown']
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  hi mkdListBlock0 guifg=#55ccff guibg=none ctermfg=14 cterm=bold
  hi mkdListBlock1 guifg=#55ccff guibg=none ctermfg=14 cterm=bold
  hi htmlH1 guifg=#ffffff guibg=#ff1000 ctermbg=196
  hi htmlH2 guifg=#ffffff guibg=#ff3000 ctermbg=165
  hi htmlH3 guifg=#ffffff guibg=#ff6000 ctermbg=90
  hi htmlH4 guifg=#ffffff guibg=#ff9000 ctermbg=54
  hi htmlH5 guifg=#ffffff guibg=#ffb000rctermbg=17

  "hi markdownCode          guibg=#333333 guifg=#cccccc ctermbg=236 ctermfg=255
  "hi markdownCodeDelimiter guibg=#222222 guifg=#cccccc ctermbg=88 ctermfg=211
  hi mkdCode guifg=#ffffff guibg=#666666 ctermbg=236 ctermfg=255
  hi mkdCodeDelimiter guifg=#ff6666 guibg=#663333 ctermbg=88 ctermfg=213
  hi mkdInlineCodeDelimiter guifg=#ff6666 guibg=#663333

  hi mkdBlockquote guifg=#cccccc guibg=#333333 ctermbg=236 ctermfg=255
'''

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  let g:previm_open_cmd = 'open -a "Google Chrome"'
'''
on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
  let g:table_mode_corner = "|"
'''
on_ft = ['markdown']
