# [[plugins]]
# repo = 'tpope/vim-markdown'
# on_ft = ['markdown']
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  hi mkdListBlock0 guifg=#55ccff guibg=none
  hi htmlH1 guifg=#ffffff guibg=#ff1000
  hi htmlH2 guifg=#ffffff guibg=#ff3000
  hi htmlH3 guifg=#ffffff guibg=#ff6000
  hi htmlH4 guifg=#ffffff guibg=#ff9000
  hi htmlH5 guifg=#ffffff guibg=#ffb000

  hi mkdCode guifg=#ffffff guibg=#666666
  hi mkdCodeDelimiter guifg=#ff6666 guibg=#663333
  hi mkdInlineCodeDelimiter guifg=#ff6666 guibg=#663333

  hi mkdBlockquote guifg=#cccccc guibg=#333333
'''

[[plugins]]
repo = 'previm/previm'
hook_add = '''
  let g:previm_open_cmd = 'open -a "Google Chrome"'
'''
on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
  let g:table_mode_corner = "|"
'''
on_ft = ['markdown']
