[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  hi mkdListBlock0 guifg=#55ccff guibg=none ctermfg=14 cterm=bold
  hi mkdListBlock1 guifg=#55ccff guibg=none ctermfg=14 cterm=bold

  hi htmlH1 ctermbg=61
  hi htmlH2 ctermbg=126
  hi htmlH3 ctermbg=90
  hi htmlH4 ctermbg=131
  hi htmlH5 ctermbg=94

  hi mkdCode guifg=#ffffff guibg=#666666 ctermbg=236 ctermfg=255
  hi mkdCodeDelimiter guifg=#ff6666 guibg=#663333 ctermbg=88 ctermfg=213
  hi mkdInlineCodeDelimiter guifg=#ff6666 guibg=#663333

  hi mkdBlockquote guifg=#cccccc guibg=#333333 ctermbg=236 ctermfg=255
'''

