[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'rake', 'eruby', 'slim']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby', 'rake', 'eruby', 'slim']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'takkii/ruby-dictionary3'
hook_add='''
  autocmd FileType ruby,slim
  \ setlocal dictionary+=~/.cache/dein/repos/github.com/takkii/ruby-dictionary3/autoload/source/ruby_method_deoplete
'''

[[plugins]]
repo='AndrewRadev/splitjoin.vim'
on_ft = ['ruby']

