# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby', 'slim']
[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby', 'eruby', 'slim']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_linters = {
  \   'ruby': ['rubocop'],
  \}

  """ " 保存時だけチェックする（編集中にチェックしない。ファイルオープン時にチェックしない）
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 0

  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0

  let g:ale_completion_autoimport = 0
  let g:ale_ruby_rubocop_executable = 'bundle'
  let g:ale_linters_explicit = 1

  let g:ale_sign_error = 'Er'
  hi ALEError ctermbg=168
  hi ALESignColumnWithErrors ctermbg=168

  let g:ale_sign_warning = 'Wa'
  hi ALEWarning ctermbg=DarkMagenta
  hi ALESignColumnWithoutErrors ctermbg=DarkMagenta
'''
on_ft = ['ruby', 'eruby', 'slim']

