[[plugins]]
repo = 'leshill/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  hi mkdListBlock0 guifg=#55ccff guibg=none ctermfg=14 cterm=bold
  hi mkdListBlock1 guifg=#55ccff guibg=none ctermfg=14 cterm=bold

  hi htmlH1 ctermbg=61
  hi htmlH2 ctermbg=126
  hi htmlH3 ctermbg=90
  hi htmlH4 ctermbg=131
  hi htmlH5 ctermbg=94

  hi mkdCode guifg=#ffffff guibg=#666666 ctermbg=236 ctermfg=255
  hi mkdCodeDelimiter guifg=#ff6666 guibg=#663333 ctermbg=88 ctermfg=213
  hi mkdInlineCodeDelimiter guifg=#ff6666 guibg=#663333

  hi mkdBlockquote guifg=#cccccc guibg=#333333 ctermbg=236 ctermfg=255

  let g:vim_markdown_folding_disabled=1
  let g:vim_markdown_liquid=1
  let g:vim_markdown_math=0
  let g:vim_markdown_frontmatter=1
  let g:vim_markdown_toml_frontmatter=1
  let g:vim_markdown_json_frontmatter=0
  set nofoldenable
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo='mechatroner/rainbow_csv'
on_ft = ['csv', 'tsv']

[[plugins]]
repo ='ap/vim-css-color'
on_ft = ['css', 'scss']

[[plugins]]
repo='stsewd/tree-sitter-rst'
on_ft = ['rst']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

