# colorschema

#[[plugins]]
#repo = 'chriskempson/vim-tomorrow-theme'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme Tomorrow-Night-Bright
#'''

#[[plugins]]
#repo = 'ntk148v/vim-horizon'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme horizon
#'''

#[[plugins]]
#repo = 'SolomonSklash/vim-snazzy'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme snazzy
#'''

#[[plugins]]
#repo = 'w0ng/vim-hybrid'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme hybrid
#'''

#[[plugins]]
#repo = 'tomasr/molokai'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme molokai
#'''

#[[plugins]]
#repo = 'znake/znake-vim'
#hook_add = '''
#  "set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme znake
#'''

#[[plugins]]
#repo = 'archSeer/colibri.vim'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme colibri
#'''

#[[plugins]]
#repo = 'cocopon/iceberg.vim'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme iceberg
#'''

#[[plugins]]
#repo = 'jacoborus/tender.vim'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme tender
#'''

#[[plugins]]
#repo = 'bruschill/madeofcode'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme madeofcode
#'''

#[[plugins]]
#repo = 'jacoborus/tender'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme tender
#'''

#[[plugins]]
#repo = 'ronny/birds-of-paradise.vim'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme birds-of-paradise
#'''

#[[plugins]]
#repo = 'yuratomo/neon.vim'
#hook_add = '''
#  set background=dark
#  au MyAutoCmd VimEnter * nested colorscheme neon
#'''

