[[plugins]]
repo='thinca/vim-quickrun'
hook_add = '''
  nnoremap <f5> :QuickRun<CR>
  vnoremap <f5> :QuickRun -mode v<CR>
  nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "<C-c>"

  let g:quickrun_config = {
  \ "_" : {
  \  "runner" : "vimproc",
  \  "runner/vimproc/updatetime" : 60,
  \  "outputter/buffer/split" : "botright 8sp",
  \  "outputter/buffer/close_on_empty" : 1
  \  },
  \ }
'''
