alias ll='ls -Ulah -D "%Y-%m-%d %H:%M:%S" --color=auto'
alias ls='ls -G'
alias vim='nvim'
alias chrome='open -a Google\ Chrome.app'
alias -g D='-w --reverse $(git merge-base develop HEAD)...HEAD'
alias -g cd..='cd ..'
