[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "d"
run = "noop"
desc = "Disable trash"

[[mgr.prepend_keymap]]
on = "D"
run = "noop"
desc = "Disable permanent delete"
