[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "d"
run = "noop"
desc = "Disable trash"

[[mgr.prepend_keymap]]
on = "D"
run = "noop"
desc = "Disable permanent delete"

[[mgr.prepend_keymap]]
on = "a"
run = "noop"
desc = "Disable create"

[[mgr.prepend_keymap]]
on = "s"
run = "noop"
desc = "Disable search via fd"

[[mgr.prepend_keymap]]
on = "t"
run = "noop"
desc = "Disable tab"
