alias ll='ls -Ulah'
alias ls='ls -G'
alias vim='nvim'
alias v='nvim'
alias -g D='-w --reverse $(git merge-base develop HEAD)...HEAD'
alias m='mkdir -p ~/memo/$(date '+%Y_%m') && nvim ~/memo/$(date '+%Y_%m')/$(date '+%Y_%m%d').md'
