#!/bin/bash
# srcdir=$1 のファイルを dstdir=$2 に同期する。
srcdir=${1%/}
dstdir=${2%/}
_sudo=$3
echo "[$(cd $(dirname $0); pwd)/$(basename $0)], srcdir=${srcdir}, dstdir=${dstdir}"

for src in $(ls ${srcdir}/*); do
  dst=${dstdir}/$(basename ${src})
  if [ "$(md5 -q ${src})" != "$(md5 -q ${dst})" ]; then
    ts=$(stat -f "%Sm" ${dst}| sed -e "s/[ ]/_/g"| sed -e "s/://g") # ex) Nov 26 19:52:00 2019 => Nov_26_195200_2019
    [[ -e ${dst} ]] && ${_sudo} cp ${dst} ${dst}_${ts}
    ${_sudo} cp ${src} ${dst}
  fi
done
