[colors.normal]
black = "#14191e"
blue = "#2743c7"
cyan = "#00c5c7"
green = "#00c200"
magenta = "#bf3fbd"
red = "#b43c29"
white = "#c7c7c7"
yellow = "#c7c400"

[colors.bright]
black = "#676767"
blue = "#a6aaf1"
cyan = "#5ffdff"
green = "#57e690"
magenta = "#e07de0"
red = "#dc7974"
white = "#feffff"
yellow = "#ece100"

[colors.primary]
background = "#111120"
foreground = "#ececec"

[font]
size =14
offset = {x=0, y=-1}
normal = {family = "Moralerspace Neon HWJPDOC"}

[[keyboard.bindings]]
key = "w"
mods = "Command"
chars = "" # Cmd+wの無効化(うっかりAlacrittyを閉じてほしくない その1)

[[keyboard.bindings]]
key = "q"
mods = "Command"
chars = "" # Cmd+qの無効化(うっかりAlacrittyを閉じてほしくない その2)

[[keyboard.bindings]]
key = "m"
mods = "Command"
chars = "" # Cmd+mの無効化(うっかり最小化しないでほしい)

[[keyboard.bindings]]
key = "t"
mods = "Command"
chars = "" # Cmd+mの無効化(うっかりタブを開かないでほしい)

# [[keyboard.bindings]]
# key = "n"
# mods = "Command"
# chars = "" # Cmd+mの無効化(うっかり新規ウインドウを開かないでほしい)

[[keyboard.bindings]]
# Karabiner elementsによって、
# JISキーボードをUSキーボード配列相当に変換した上で、
# JISキーボード上の `Command+~`を押した時にフォントサイズを拡大する。
# PS: なぜ`~`の押下を`key = ";"`と表現しているのか、というのを説明するのが難しいが、
# .config/karabiner/assets/complex_modifications/50_jis_to_us.jsonの
# "description": "Change command + ^ to expand(IncreaseFontSize)" あたりを見るとわかるかもしれない。
key = ";"
mods = "Command"
action = "IncreaseFontSize"

[window]
decorations = "full"
opacity = 1.0

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
