[colors.bright]
black = "#676767"
blue = "#6871ff"
cyan = "#5ffdff"
green = "#5ff967"
magenta = "#ff76ff"
red = "#ff6d67"
white = "#feffff"
yellow = "#fefb67"

[colors.normal]
black = "#000000"
blue = "#0225c7"
cyan = "#00c5c7"
green = "#00c200"
magenta = "#c930c7"
red = "#c91b00"
white = "#c7c7c7"
yellow = "#c7c400"

[colors.primary]
background = "#000000"
foreground = "#c7c7c7"

[font]
size = 20
offset = {x=0, y=-2}
#normal = {family = "Noto Mono for Powerline"}
#normal = {family = "JetBrainsMono Nerd Font Mono"}
#normal = {family = "Source code Pro for Powerline"}
#normal = {family = "Inconsolata-g for Powerline"}
normal = {family = "Inconsolata-dz for Powerline"}

[[keyboard.bindings]]
key = "F11"
chars = "\u0014n" # これは<ctrl-t>n

[[keyboard.bindings]]
key = "F11"
mods = "Shift"
chars = "\u0014N" # これは<ctrl-t>N

[[keyboard.bindings]]
key = "F12"
chars = "\u0014z" # これは<ctrl-t>z

[shell]
args = ["-l"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "full"
opacity = 0.8

